# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.cache/wt [current_project]
set_property parent.project_path /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.srcs/sources_1/new/adder_datapath.vhd
  /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.srcs/sources_1/new/adder_controller.vhd
  /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.srcs/sources_1/new/mega_adder.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.srcs/constrs_1/new/mega_adder_constraints.xdc
set_property used_in_implementation false [get_files /home/sindre/Documents/NTNU/16-2/TFE4141/assignments/assignment5/assignment_5.srcs/constrs_1/new/mega_adder_constraints.xdc]


synth_design -top mega_adder -part xc7z020clg484-1


write_checkpoint -force -noxdef mega_adder.dcp

catch { report_utilization -file mega_adder_utilization_synth.rpt -pb mega_adder_utilization_synth.pb }
