# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/student/Documents/TFE4141_GR17/assignment4/assignment4.cache/wt [current_project]
set_property parent.project_path C:/Users/student/Documents/TFE4141_GR17/assignment4/assignment4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib C:/Users/student/Documents/TFE4141_GR17/assignment4/assignment4.srcs/sources_1/new/task1.vhd
synth_design -top thing_with_latch -part xc7z020clg484-1
write_checkpoint -noxdef thing_with_latch.dcp
catch { report_utilization -file thing_with_latch_utilization_synth.rpt -pb thing_with_latch_utilization_synth.pb }
